### Get all ccsp
GET http://localhost:8080/api/ccsps
Content-Type: application/json

###
GET http://localhost:8080/api/ccsp/courses
Content-Type: application/json

### Get a ccsp by code
GET http://localhost:8080/api/ccsps/1
Content-Type: application/json

### Crate a ccsp
POST http://localhost:8080/api/ccsps
Content-Type: application/json

{
    "name": "CSE OBE (4M)",
    "departmentCode": "1010",
    "offeredTerm": [4, 5],
    "isOptional": [false, false],
    "credits": 40,
    "terms": 8
}