### Get all department
GET http://localhost:8080/api/departments
Content-Type: application/json

### Get a department by code
GET http://localhost:8080/api/departments/DEPT13
Content-Type: application/json