### Get all department
GET http://localhost:8080/api/departments
Content-Type: application/json

### Get a department by code
GET http://localhost:8080/api/departments/DEPT11
Content-Type: application/json

### Get a department by code with all it's ccsps
GET http://localhost:8080/api/departments/DEPT12/ccsps
Content-Type: application/json
